version: '2.4'

services:
  api:
    build:
      context: ./
      dockerfile: .dockerfiles/apiDev
    ports:
      - '9000:9000'
    environment:
      - FLASK_ENV=development
    volumes:
      - './api:/api'
    restart: always

  db:
    build:
      context: ./
      dockerfile: .dockerfiles/db
    ports:
      - '5432:5432'
    volumes:
      - /var/lib/postgresql/data
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  grafana:
    image: grafana/grafana
    environment:
      - "GF_SECURITY_ADMIN_USER=smart"
      - "GF_SECURITY_ADMIN_PASSWORD=smart"
    ports:
      - 3000:3000